language: node_js
node_js:
  - "4.1"
sudo: required
dist: trusty
before_install:
  - export CHROME_BIN=google-chrome-beta
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-beta
  - npm install -g protractor
  - npm install -g webdriver-manager
script:
  - npm run build
  - npm run ci-test
  - npm run ci-e2e-test
